// Command gen-nested writes M sections of N pages each directly into a
// LeafWiki data directory's root/, for load-testing Delete/Move scenarios
// against a real subtree (loadtest/README.md and
// plans/loadtest-additional-scenarios.md need this — gen-pages only
// produces flat pages).
//
// Layout: root/section-NN/index.md (the section's own content) plus
// root/section-NN/page-NNNNN.md for each page in that section. Matches
// exactly what internal/core/tree/node_store.go's ReconstructTreeFromFSContext
// expects (confirmed against node_store_reconstruct_test.go fixtures during
// the original gen-pages work): a directory is a section, its own
// frontmatter/content lives at <dir>/index.md.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"
)

const sectionIndexTemplate = `---
leafwiki_id: %s
leafwiki_title: %s
leafwiki_created_at: %q
leafwiki_updated_at: %q
leafwiki_creator_id: system
leafwiki_last_author_id: system
---
# %s

Seed section for load testing (loadtest/seed/gen-nested), not meant to be
edited by hand.
`

const pageTemplate = `---
leafwiki_id: %s
leafwiki_title: %s
leafwiki_created_at: %q
leafwiki_updated_at: %q
leafwiki_creator_id: system
leafwiki_last_author_id: system
---
# %s

Seed content for LeafWiki load testing. This page was generated by
loadtest/seed/gen-nested and is not meant to be edited by hand.
`

func main() {
	sections := flag.Int("sections", 10, "number of sections to generate")
	pagesPerSection := flag.Int("pages-per-section", 50, "number of pages inside each section")
	startIndex := flag.Int("start-index", 1, "first section number to use — lets multiple runs into the same data dir occupy disjoint section-NN ranges (e.g. a small-subtree tier and a large-subtree tier side by side)")
	dir := flag.String("dir", "", "path to the LeafWiki data directory (root/ is created inside it)")
	flag.Parse()

	if *dir == "" {
		log.Fatal("gen-nested: --dir is required (path to the LeafWiki data directory)")
	}

	rootDir := filepath.Join(*dir, "root")
	if err := os.MkdirAll(rootDir, 0o755); err != nil {
		log.Fatalf("gen-nested: creating %s: %v", rootDir, err)
	}

	now := time.Now().UTC().Format(time.RFC3339)

	for s := *startIndex; s < *startIndex+*sections; s++ {
		sectionSlug := fmt.Sprintf("section-%03d", s)
		sectionTitle := fmt.Sprintf("Load Test Section %03d", s)
		sectionDir := filepath.Join(rootDir, sectionSlug)
		if err := os.MkdirAll(sectionDir, 0o755); err != nil {
			log.Fatalf("gen-nested: creating %s: %v", sectionDir, err)
		}

		indexContent := fmt.Sprintf(sectionIndexTemplate, sectionSlug, sectionTitle, now, now, sectionTitle)
		indexPath := filepath.Join(sectionDir, "index.md")
		if err := os.WriteFile(indexPath, []byte(indexContent), 0o644); err != nil {
			log.Fatalf("gen-nested: writing %s: %v", indexPath, err)
		}

		for p := 1; p <= *pagesPerSection; p++ {
			pageID := fmt.Sprintf("%s-page-%05d", sectionSlug, p)
			pageTitle := fmt.Sprintf("%s Page %05d", sectionTitle, p)
			content := fmt.Sprintf(pageTemplate, pageID, pageTitle, now, now, pageTitle)

			pagePath := filepath.Join(sectionDir, fmt.Sprintf("page-%05d.md", p))
			if err := os.WriteFile(pagePath, []byte(content), 0o644); err != nil {
				log.Fatalf("gen-nested: writing %s: %v", pagePath, err)
			}
		}

		fmt.Printf("gen-nested: section %s written (%d pages)\n", sectionSlug, *pagesPerSection)
	}

	fmt.Printf("gen-nested: done, %d sections (section-%03d..section-%03d) x %d pages written under %s\n",
		*sections, *startIndex, *startIndex+*sections-1, *pagesPerSection, rootDir)
}
