// Command gen-linked writes a controllable number of "hub" pages plus N
// "linker" pages per hub, each linker containing a [[Title]] wikilink to
// its hub, directly into a LeafWiki data directory's root/. Used to
// load-test rename + link-refactor (plans/loadtest-additional-scenarios.md
// Scenario 4): renaming a hub with a large in-degree is the expensive case
// for MarkdownRefactorEngine, and this needs seed data gen-pages doesn't
// produce (gen-pages' pages contain no links at all).
//
// [[Title]] links are resolved by exact title match at index time
// (internal/links, LinkIndexSideEffect / the boot-time IndexAllPagesContext
// pass) — not written by this tool, which only writes the raw markdown
// containing the wikilink syntax. The server's normal startup indexing
// (ReloadFromFS -> IndexAllPagesContext for links) picks these up on first
// boot the same way it would for any other page, no special handling
// needed here.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"
)

const hubTemplate = `---
leafwiki_id: %s
leafwiki_title: %s
leafwiki_created_at: %q
leafwiki_updated_at: %q
leafwiki_creator_id: system
leafwiki_last_author_id: system
---
# %s

Seed hub page for load testing (loadtest/seed/gen-linked) — the target of
many inbound [[Title]] wikilinks, not meant to be edited by hand.
`

const linkerTemplate = `---
leafwiki_id: %s
leafwiki_title: %s
leafwiki_created_at: %q
leafwiki_updated_at: %q
leafwiki_creator_id: system
leafwiki_last_author_id: system
---
# %s

Seed content for LeafWiki load testing, linking to [[%s]].
This page was generated by loadtest/seed/gen-linked and is not meant to be
edited by hand.
`

func main() {
	hubs := flag.Int("hubs", 3, "number of hub pages to generate")
	linkersPerHub := flag.Int("linkers-per-hub", 100, "number of pages linking to each hub (in-degree)")
	hubStartIndex := flag.Int("hub-start-index", 1, "first hub number to use — lets multiple runs into the same data dir occupy disjoint hub-NN ranges (e.g. a low-in-degree tier and a high-in-degree tier side by side)")
	dir := flag.String("dir", "", "path to the LeafWiki data directory (root/ is created inside it)")
	flag.Parse()

	if *dir == "" {
		log.Fatal("gen-linked: --dir is required (path to the LeafWiki data directory)")
	}

	rootDir := filepath.Join(*dir, "root")
	if err := os.MkdirAll(rootDir, 0o755); err != nil {
		log.Fatalf("gen-linked: creating %s: %v", rootDir, err)
	}

	now := time.Now().UTC().Format(time.RFC3339)

	for h := *hubStartIndex; h < *hubStartIndex+*hubs; h++ {
		hubSlug := fmt.Sprintf("hub-%03d", h)
		hubTitle := fmt.Sprintf("Load Test Hub %03d", h)
		hubContent := fmt.Sprintf(hubTemplate, hubSlug, hubTitle, now, now, hubTitle)
		hubPath := filepath.Join(rootDir, hubSlug+".md")
		if err := os.WriteFile(hubPath, []byte(hubContent), 0o644); err != nil {
			log.Fatalf("gen-linked: writing %s: %v", hubPath, err)
		}

		for l := 1; l <= *linkersPerHub; l++ {
			linkerID := fmt.Sprintf("%s-linker-%05d", hubSlug, l)
			linkerTitle := fmt.Sprintf("%s Linker %05d", hubTitle, l)
			content := fmt.Sprintf(linkerTemplate, linkerID, linkerTitle, now, now, linkerTitle, hubTitle)

			linkerPath := filepath.Join(rootDir, linkerID+".md")
			if err := os.WriteFile(linkerPath, []byte(content), 0o644); err != nil {
				log.Fatalf("gen-linked: writing %s: %v", linkerPath, err)
			}
		}

		fmt.Printf("gen-linked: hub %s written (%d linkers)\n", hubSlug, *linkersPerHub)
	}

	fmt.Printf("gen-linked: done, %d hubs (hub-%03d..hub-%03d) with %d linkers each written under %s\n",
		*hubs, *hubStartIndex, *hubStartIndex+*hubs-1, *linkersPerHub, rootDir)
}
