// Command gen-pages writes N flat page markdown files directly into a
// LeafWiki data directory's root/ folder, for fast load-test seeding.
//
// Going through POST /api/pages N times would serialize on the same global
// tree lock the load test is meant to measure, and would take far longer
// than a direct write. This tool bypasses the API entirely: the normal
// ReconstructTreeFromFSContext startup path (internal/core/tree/node_store.go)
// picks these files up like any other on-disk page.
//
// Frontmatter is pre-populated (leafwiki_id, timestamps, author) so the
// first server startup against the generated directory is pure-read, with
// no writeback churn to fill in missing managed fields.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"
)

const pageTemplate = `---
leafwiki_id: %s
leafwiki_title: %s
leafwiki_created_at: %q
leafwiki_updated_at: %q
leafwiki_creator_id: system
leafwiki_last_author_id: system
---
# %s

Seed content for LeafWiki load testing. This page was generated by
loadtest/seed/gen-pages and is not meant to be edited by hand.
`

func main() {
	count := flag.Int("count", 10000, "number of pages to generate")
	dir := flag.String("dir", "", "path to the LeafWiki data directory (root/ is created inside it)")
	flag.Parse()

	if *dir == "" {
		log.Fatal("gen-pages: --dir is required (path to the LeafWiki data directory)")
	}

	rootDir := filepath.Join(*dir, "root")
	if err := os.MkdirAll(rootDir, 0o755); err != nil {
		log.Fatalf("gen-pages: creating %s: %v", rootDir, err)
	}

	now := time.Now().UTC().Format(time.RFC3339)

	for i := 1; i <= *count; i++ {
		id := fmt.Sprintf("page-%05d", i)
		title := fmt.Sprintf("Load Test Page %05d", i)
		content := fmt.Sprintf(pageTemplate, id, title, now, now, title)

		path := filepath.Join(rootDir, id+".md")
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			log.Fatalf("gen-pages: writing %s: %v", path, err)
		}

		if i%1000 == 0 {
			fmt.Printf("gen-pages: %d/%d pages written\n", i, *count)
		}
	}

	fmt.Printf("gen-pages: done, %d pages written to %s\n", *count, rootDir)
}
